---
title: "Bio302 Home Exam 2024 Part A"
format: 
  html:
    self-contained: true
    code-tools: 
      source: true
---

## Part A - reproducibility

Choose a paper that:
    -  interests you
    -  claims to have open data
    -  uses methods that you can use

Identify the main result and try to reproduce it from the available data, the description of the methods, and other resources (if the paper has several main results, choose one). Spend no more than 2-3 hours on this (if it takes longer, the paper was not easy to reproduce!).

If you are trying to reproduce a figure, there is not need to match colour scales etc, just the scientific content.

Archive the code and text on GitHub and include the link to your repo in your answer here.

-   Make at least two commits to git.
-   Cite the original paper and data.
-   Make your reproduction as reproducible as possible (i.e. it should be possible for me to reproduce your work after cloning your repo and downloading the data).

1.  Discuss how well you managed to reproduce the part of paper you were working on and what challenges you faced.

3.  Discuss what how well the original paper meets best practice for reproducibility, i.e. what could the authors have done to make their analysis more reproducible, and what they did well.

- not easy to find open data in the first place, databases with papers and corresponding datasets could be better and more papers should have openly accessible datasets
